### ISSUE TITLE
Initializing Memberships issue

### ISSUE THREAD

**Issue by rhenryrobert** [pubnub/typescript-ref-app-team-chat#6]
Not able to install.. getting this error.

**Initializing Memberships :**
`PubNubError(PNSetMembersOperation): PNTimeoutCategory.ECONNABORTED`

FYI : 
Tried `npm run setup` also.

Screenshot : 
![image](https://user-images.githubusercontent.com/7262633/92238748-736b1b80-eed7-11ea-83aa-7607a4623a83.png)

**Comment by Nickman87** [comment]
Same here...

**Comment by Salet** [comment]
Hi @rhenryrobert and @Nickman87, sorry for a late reply.
What is the Objects Region you set up for your keyset within PubNub admin? And does it match the actual location of the computer you are installing the app on?

![Screen Shot 2020-09-23 at 1 34 53 PM](https://user-images.githubusercontent.com/1308234/94007345-9b94be80-fda1-11ea-9c46-ff4efad01fe0.png)

**Comment by Nickman87** [comment]
Apparently it is set to US EAST
![image](https://user-images.githubusercontent.com/870416/95213539-3607ef80-07ef-11eb-9125-1300d3a4819a.png)
But I am not able to change it it seems?

I am situated in Europe, so that might be the issue?

**Comment by Salet** [comment]
Yes, that setting is why the the script is timing out for you if your actual location doesn't match. Objects are supposed be set on a region where most of the clients will query for them. Changing the script to overcome such setting is on my backlog, however it will take some time to deploy it. 

As far as I know once the Objects region is set you cannot change it by yourself. In the meantime, if that is an option, you can create a new, fresh set of PN keys and enable Objects accordingly. Otherwise you should contact support to see if they can change the region for you on your current set of keys, or I can share a way to change the script that should work.

Anyway, the script is timing out on assigning users to channels. If that functionality is not essential to you then you can just skip this altogether. This way you just won't see any channel members on the panel on the right.

**Comment by Salet** [comment]
Closing the issue for now, please let us know if this causes any further problems
